# Generated by Django 5.0.3 on 2024-03-19 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='Sorts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('shade', models.CharField(max_length=255, verbose_name='Оттенок')),
                ('image', models.ImageField(upload_to='photos/<django.db.models.fields.CharField>/')),
                ('planted', models.IntegerField(verbose_name='Посажено')),
                ('collected', models.IntegerField(verbose_name='Собрано')),
                ('died', models.IntegerField(verbose_name='Погибло')),
                ('sold', models.IntegerField(verbose_name='Продано')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_price', models.CharField(max_length=255, verbose_name='Итоговая стоимость')),
                ('prepayment', models.CharField(max_length=255, verbose_name='Предоплата')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('time', models.DateTimeField(verbose_name='Время')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesale.clients')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesale.orders')),
                ('sort_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesale.sorts')),
            ],
        ),
    ]
