# Generated by Django 5.0.3 on 2024-03-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='time',
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(verbose_name='Дата и Время'),
        ),
    ]
