# Generated by Django 5.0.3 on 2024-03-19 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0002_remove_orders_time_alter_orders_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='sort_id',
            new_name='sort',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='client_id',
            new_name='client',
        ),
    ]
