# Generated by Django 5.0.3 on 2024-04-03 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0003_rename_order_id_orderdetails_order_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='OrderDetails',
            new_name='OrderDetail',
        ),
        migrations.RenameModel(
            old_name='Sorts',
            new_name='Sort',
        ),
    ]
